name: Bug Report
description: File a bug/issue for the core language
title: "[Bug] <title>"
labels: [Bug, Question]
assignees: Luna-Klatzer
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please [search here](https://github.com/Luna-Klatzer/Kipper/issues) to see if an issue already exists for your problem.
    options:
    - label: I have searched the existing issues
      required: true
- type: checkboxes
  attributes:
    label: I am following the documentation's guide
    description: Please make sure you followed the documentation and the error appears despite correct usage.
    options:
      - label: I have read the documentation
        required: true
- type: checkboxes
  attributes:
    label: This issue exists in the latest version
    description: Please make sure you have installed the latest Kipper version and verified it is still an issue.
    options:
    - label: I am using the latest version
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A clear & concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear & concise description of what you expected to happen. Use function and class names if possible to simplify finding the error, for example `CompilableParseToken.translateCtxAndChildren`.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    value: |
      1. Go to '...'
      2. Utilise/Call '...' with param '...'
      3. See error
  validations:
   required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **Kipper**: 0.3.0
        - **Operating System **: Ubuntu 20.04
    value: |
      - Kipper:
      - Operating System (+ Version):
  validations:
    required: false
