blank_issues_enabled: false
contact_links:
  - name: Project Documentation
    url: https://luna-klatzer.github.io/Kipper/docs/
    about: If you have any general question about the Kipper project or language, you will likely find your answer here.
