name: Feature Request
description: File an enhancement proposal for the language, compiler or library.
title: "[Feature] <title>"
labels: [Feature, Question]
assignees: Luna-Klatzer
body:
  - type: checkboxes
    attributes:
      label: Is there an existing proposal for this?
      description: Please [search here](https://github.com/npm/cli/issues) to see if an issue already exists for your problem.
      options:
        - label: I have searched the existing issues
          required: true
  - type: checkboxes
    attributes:
      label: This feature does not exist in the latest version
      description: Please make sure you have installed the latest Kipper version and verify the feature is not implemented.
      options:
        - label: I am using the latest version
          required: true
  - type: textarea
    attributes:
      label: Proposal
      description: A clear & concise description of what you want to be added into the language, compiler or library.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Exact behaviour you want
      description: Describe how the feature could look like and how you would use it.
    validations:
      required: false
