/**
 * Antlr4 listener for walking through a parser tree and processing its content.
 * @author Luna Klatzer
 * @copyright 2021-2022 Luna Klatzer
 * @since 0.0.3
 */
import type {
	ActualAdditiveExpressionContext,
	ActualAssignmentExpressionContext,
	ActualCastOrConvertExpressionContext,
	ActualConditionalExpressionContext,
	ActualEqualityExpressionContext,
	ActualLogicalAndExpressionContext,
	ActualLogicalOrExpressionContext,
	ActualMultiplicativeExpressionContext,
	ActualRelationalExpressionContext,
	ArraySpecifierContext,
	ArraySpecifierPostfixExpressionContext,
	AssignmentOperatorContext,
	CharacterPrimaryExpressionContext,
	CompoundStatementContext,
	DeclarationContext,
	DeclarationSpecifierContext,
	DeclarationSpecifiersContext,
	DeclaratorContext,
	DirectDeclaratorContext,
	ExpressionStatementContext,
	ExternalBlockItemContext,
	ExternalFunctionDeclarationContext,
	FStringPrimaryExpressionContext,
	FunctionCallPostfixExpressionContext,
	FunctionDeclarationContext,
	IdentifierPrimaryExpressionContext,
	IncrementOrDecrementPostfixExpressionContext,
	IncrementOrDecrementUnaryExpressionContext,
	InitDeclaratorContext,
	InitializerContext,
	IterationStatementContext,
	JumpStatementContext,
	KipperListener,
	ListPrimaryExpressionContext,
	NumberPrimaryExpressionContext,
	OperatorModifiedUnaryExpressionContext,
	ParameterDeclarationContext,
	ParameterListContext,
	ParameterTypeListContext,
	GenericTypeSpecifierContext,
	StorageTypeSpecifierContext,
	StringPrimaryExpressionContext,
	SwitchLabeledStatementContext,
	TangledPrimaryExpressionContext,
	TypeofTypeSpecifierContext,
	TypeSpecifierContext,
	UnaryOperatorContext,
	BoolPrimaryExpressionContext,
	SingleTypeSpecifierContext,
	CompilationUnitContext,
} from "./index";
import type { KipperProgramContext } from "../program-ctx";
import { ParserRuleContext } from "antlr4ts";
import {
	type antlrDefinitionCtxType,
	type antlrExpressionCtxType,
	type antlrStatementCtxType,
	Declaration,
	Statement,
	Expression,
	getDefinitionInstance,
	getExpressionInstance,
	getStatementInstance,
} from "../semantics";
import { IfStatementContext, SwitchStatementContext } from "./index";
import { RootASTNode } from "./root-ast-node";
import { CompilableASTNode } from "./compilable-ast-node";

const passOnHandler = undefined;

/**
 * The listener for a {@link KipperProgramContext}, which walks through a parse tree generated by Antlr4 and generates
 * an abstract syntax tree based on the parse tree.
 * @author Luna Klatzer
 * @copyright 2021-2022 Luna Klatzer
 * @since 0.0.3
 */
export class KipperFileListener implements KipperListener {
	/**
	 * The private field '_itemBuffer' that actually stores the variable data,
	 * which is returned inside the {@link this.itemBuffer}.
	 * @private
	 */
	private readonly _rootNode: RootASTNode;

	/**
	 * If this is true, the current context is inside an external item and automatically indicates
	 * {@link _isFunctionDefinition} is false.
	 */
	private _isExternalItem: boolean;

	/**
	 * If this is true, the current context is inside a function definition and automatically indicates
	 * {@link _isExternalItem} is false.
	 */
	private _isFunctionDefinition: boolean;

	/**
	 * The current Kipper AST node that is being walked through right now. This is the instance where current metadata
	 * should be added to and read from, as this instance will represent and handle the context rules that were walked
	 * through during this operation.
	 */
	private _currentPrimaryNode: CompilableASTNode<any> | undefined;

	/**
	 * The current expression that is being walked through. This is the instance where current metadata
	 * should be added to and read from, as this instance will represent and handle the context rules that were walked
	 * through during this operation.
	 */
	private _currentExpression: Expression<any> | undefined;

	constructor(programCtx: KipperProgramContext, rootNode: CompilationUnitContext) {
		this._rootNode = new RootASTNode(programCtx, rootNode);
		this._isExternalItem = false;
		this._isFunctionDefinition = false;
		this._currentPrimaryNode = undefined;
	}

	/**
	 * The root node of the generated abstract syntax tree.
	 * @since 0.8.0
	 */
	public get rootNode(): RootASTNode {
		return this._rootNode;
	}

	/**
	 * Returns which token is being processed at the moment and where meta-data should be assigned to. If
	 * {@link _currentExpression} is defined, then that item will be returned, otherwise {@link _currentPrimaryNode}.
	 * @private
	 */
	private get getCurrentNode(): CompilableASTNode<any> | RootASTNode {
		if (this._currentExpression) {
			return this._currentExpression;
		} else if (this._currentPrimaryNode) {
			return this._currentPrimaryNode;
		} else {
			return this.rootNode;
		}
	}

	/**
	 * Handles an incoming expression context. The handling algorithm is:
	 * - If {@link _currentExpression} is undefined, then it will be created and set as a child of the
	 * {@link _currentPrimaryNode}.
	 * - Otherwise, generate a new {@link Expression} instance, which will be added to the {@link _currentExpression} as
	 * a child. Afterwards {@link _currentExpression} will be set to this new instance, as all new context instances
	 * must be assigned to it. When the context is left, then the old {@link _currentExpression} will be restored as
	 * {@link _currentExpression}, and all further context instances will be assigned to it.
	 * @param ctx The context instance of the expression
	 * @private
	 */
	private handleIncomingExpressionCtx(ctx: antlrExpressionCtxType) {
		if (this.getCurrentNode instanceof RootASTNode) {
			throw new Error(
				"An expression may not have the root file token as a parent. It must be child to a statement or a" +
					" definition.",
			);
		}

		this._currentExpression = getExpressionInstance(ctx, this.getCurrentNode);
	}

	/**
	 * Handles an exiting expression context. The handling algorithm is:
	 * - If {@link _currentExpression.parent} is of type {@link Expression}, then set {@link _currentExpression} to
	 * that parent.
	 * - Otherwise set {@link _currentExpression} to {@link undefined} again. If  {@link handleIncomingExpressionCtx} is
	 * called again, the {@link _currentExpression} will be defined again and the whole process starts again.
	 * @private
	 */
	private handleExitingExpressionCtx() {
		if (this._currentExpression?.parent instanceof Expression) {
			this._currentExpression = this._currentExpression.parent;
		} else {
			this._currentExpression = undefined;
		}
	}

	/**
	 * Handles an incoming statement context. The handling algorithm is:
	 * - If {@link _currentPrimaryNode} is undefined, then it will be created and set as a child of
	 * {@link _rootNode}
	 * - Otherwise, generate a new {@link Statement} instance, which will be added to the {@link _currentPrimaryNode} as
	 * a child. Afterwards {@link _currentPrimaryNode} will be set to this new instance, as all new context instances
	 * must be assigned to it. When the context is left, then the old {@link _currentPrimaryNode} will be restored as
	 * {@link _currentPrimaryNode}, and all further context instances will be assigned to it.
	 * @private
	 */
	private handleIncomingStatementCtx(ctx: antlrStatementCtxType) {
		this._currentPrimaryNode = getStatementInstance(ctx, this.getCurrentNode);
	}

	/**
	 * Handles an incoming statement context. The handling algorithm is:
	 * - If {@link _currentPrimaryNode} is undefined, then it will be created and set as a child of
	 * {@link _rootNode}
	 * - Otherwise, generate a new {@link Declaration} instance, which will be added to the {@link _currentPrimaryNode} as
	 * a child. Afterwards {@link _currentPrimaryNode} will be set to this new instance, as all new context instances
	 * must be assigned to it. When the context is left, then the old {@link _currentPrimaryNode} will be restored as
	 * {@link _currentPrimaryNode}, and all further context instances will be assigned to it.
	 * @private
	 */
	private handleIncomingDefinitionCtx(ctx: antlrDefinitionCtxType) {
		this._currentPrimaryNode = getDefinitionInstance(ctx, this.getCurrentNode);
	}

	/**
	 * Handles an exiting statement or definition context. The handling algorithm is:
	 * - If {@link _currentPrimaryNode.parent} is of type {@link _currentPrimaryNode} or {@link Statement}, then set
	 * {@link _currentPrimaryNode} to that parent.
	 * - Otherwise set {@link _currentPrimaryNode} to {@link undefined} again. If
	 * {@link handleExitingStatementOrDefinitionCtx} is called again, the {@link _currentPrimaryNode} will be defined
	 * again and the whole process starts again.
	 * @private
	 */
	private handleExitingStatementOrDefinitionCtx() {
		if (
			this._currentPrimaryNode?.parent instanceof Declaration ||
			this._currentPrimaryNode?.parent instanceof Statement
		) {
			this._currentPrimaryNode = this._currentPrimaryNode.parent;
		} else {
			this._currentPrimaryNode = undefined;
		}
	}

	/**
	 * Function that is called every time an item is entered.
	 * @param ctx The context of the rule
	 */
	// eslint-disable-next-line no-unused-vars
	public enterEveryRule(/*@NotNull*/ ctx: ParserRuleContext): void {}

	/**
	 * Function that is called every time an item is exited.
	 * @param ctx The context of the rule.
	 */
	// eslint-disable-next-line no-unused-vars
	public exitEveryRule(/*@NotNull*/ ctx: ParserRuleContext): void {}

	// -- Top Item Section --

	/**
	 * Enter a parse tree produced by the `externalFunctionDeclaration`
	 * Labeled alternative in `KipperParser.externalItem`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterExternalFunctionDeclaration(ctx: ExternalFunctionDeclarationContext): void {
		// We don't check if this is a declaration, as if it were, then there will be no children that
		// need to know they are in a function definition.
		this._isFunctionDefinition = true;
	}

	/**
	 * Exit a parse tree produced by the `externalFunctionDeclaration`
	 * Labeled alternative in `KipperParser.externalItem`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitExternalFunctionDeclaration(ctx: ExternalFunctionDeclarationContext): void {
		this._isFunctionDefinition = false;
	}

	/**
	 * Enter a parse tree produced by the `externalBlockItem`
	 * Labeled alternative in `KipperParser.externalItem`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterExternalBlockItem(ctx: ExternalBlockItemContext): void {
		this._isExternalItem = true;
	}

	/**
	 * Exit a parse tree produced by the `externalBlockItem`
	 * Labeled alternative in `KipperParser.externalItem`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitExternalBlockItem(ctx: ExternalBlockItemContext): void {
		this._isExternalItem = false;
	}

	// -- Expression Section --

	/**
	 * We are ignoring primary expressions, and only going to handle the rules 'identifierPrimaryExpression'
	 * 'constantPrimaryExpression', 'stringPrimaryExpression', 'fStringPrimaryExpression' and
	 * 'tangledPrimaryExpression', which implement a more precise 'primaryExpression' rule.
	 *
	 * This is to simplify the walking process, without having to check if the expression is actually used every time
	 * an expression is called.
	 */

	// /**
	//  * Enter a parse tree produced by `KipperParser.primaryExpression`.
	//  *
	//  * This is the lowest expression / This has the highest importance of all!
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// enterPrimaryExpression(ctx: PrimaryExpressionContext): void {}
	//
	// /**
	//  * Exit a parse tree produced by `KipperParser.primaryExpression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// exitPrimaryExpression(ctx: PrimaryExpressionContext): void {}

	/**
	 * Enter a parse tree produced by the `identifierPrimaryExpression`
	 * Labeled alternative in `KipperParser.primaryExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterIdentifierPrimaryExpression(ctx: IdentifierPrimaryExpressionContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `identifierPrimaryExpression`
	 * Labeled alternative in `KipperParser.primaryExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitIdentifierPrimaryExpression(ctx: IdentifierPrimaryExpressionContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * Enter a parse tree produced by the `stringPrimaryExpression`
	 * Labeled alternative in `KipperParser.primaryExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterStringPrimaryExpression(ctx: StringPrimaryExpressionContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `stringPrimaryExpression`
	 * Labeled alternative in `KipperParser.primaryExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitStringPrimaryExpression(ctx: StringPrimaryExpressionContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * Enter a parse tree produced by the `fStringPrimaryExpression`
	 * Labeled alternative in `KipperParser.primaryExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterFStringPrimaryExpression(ctx: FStringPrimaryExpressionContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `fStringPrimaryExpression`
	 * Labeled alternative in `KipperParser.primaryExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitFStringPrimaryExpression(ctx: FStringPrimaryExpressionContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * Enter a parse tree produced by the `tangledPrimaryExpression`
	 * Labeled alternative in `KipperParser.primaryExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterTangledPrimaryExpression(ctx: TangledPrimaryExpressionContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `tangledPrimaryExpression`
	 * Labeled alternative in `KipperParser.primaryExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitTangledPrimaryExpression(ctx: TangledPrimaryExpressionContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * Enter a parse tree produced by the `numberPrimaryExpression`
	 * labeled alternative in `KipperParser.PrimaryExpression`.
	 * @param ctx The parse tree
	 */
	public enterNumberPrimaryExpression(ctx: NumberPrimaryExpressionContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `numberPrimaryExpression`
	 * labeled alternative in `KipperParser.PrimaryExpression`.
	 * @param ctx The parse tree
	 */
	public exitNumberPrimaryExpression(ctx: NumberPrimaryExpressionContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * Enter a parse tree produced by the `characterPrimaryExpression`
	 * labeled alternative in `KipperParser.PrimaryExpression`.
	 * @param ctx The parse tree
	 */
	public enterCharacterPrimaryExpression(ctx: CharacterPrimaryExpressionContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `characterPrimaryExpression`
	 * labeled alternative in `KipperParser.PrimaryExpression`.
	 * @param ctx The parse tree
	 */
	public exitCharacterPrimaryExpression(ctx: CharacterPrimaryExpressionContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * Enter a parse tree produced by the `listConstantPrimaryExpression`
	 * labeled alternative in `KipperParser.primaryExpression`.
	 * @param ctx The parse tree
	 */
	public enterListPrimaryExpression(ctx: ListPrimaryExpressionContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `listConstantPrimaryExpression`
	 * labeled alternative in `KipperParser.primaryExpression`.
	 * @param ctx The parse tree
	 */
	public exitListPrimaryExpression(ctx: ListPrimaryExpressionContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * Enter a parse tree produced by the `boolPrimaryExpression`
	 * labeled alternative in `KipperParser.primaryExpression`.
	 * @param ctx The parse tree
	 */
	public enterBoolPrimaryExpression(ctx: BoolPrimaryExpressionContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `boolPrimaryExpression`
	 * labeled alternative in `KipperParser.primaryExpression`.
	 * @param ctx The parse tree
	 */
	public exitBoolPrimaryExpression(ctx: BoolPrimaryExpressionContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * We are ignoring postfix expressions, and only going to handle the rules 'referenceExpression' and
	 * 'functionCallExpression', which implement a more precise 'postfixExpression' rule.
	 *
	 * This is to simplify the walking process, without having to check if the expression is actually used every time
	 * an expression is called.
	 */

	// /**
	//  * Enter a parse tree produced by `KipperParser.postfixExpression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// enterPostfixExpression(ctx: PostfixExpressionContext): void {}
	//
	// /**
	//  * Exit a parse tree produced by `KipperParser.postfixExpression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// exitPostfixExpression(ctx: PostfixExpressionContext): void {}

	/**
	 * Enter a parse tree produced by the `passOnPostfixExpression`
	 * Labeled alternative in `KipperParser.postfixExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterPassOnPostfixExpression: undefined = passOnHandler; // pass on expressions are always ignored

	/**
	 * Exit a parse tree produced by the `passOnPostfixExpression`
	 * Labeled alternative in `KipperParser.postfixExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitPassOnPostfixExpression: undefined = passOnHandler; // pass on expressions are always ignored

	/**
	 * Enter a parse tree produced by the `arraySpecifierPostfixExpression`
	 * Labeled alternative in `KipperParser.postfixExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterArraySpecifierPostfixExpression(ctx: ArraySpecifierPostfixExpressionContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `arraySpecifierPostfixExpression`
	 * Labeled alternative in `KipperParser.postfixExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitArraySpecifierPostfixExpression(ctx: ArraySpecifierPostfixExpressionContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * Enter a parse tree produced by the `incrementOrDecrementPostfixExpression`
	 * Labeled alternative in `KipperParser.postfixExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterIncrementOrDecrementPostfixExpression(ctx: IncrementOrDecrementPostfixExpressionContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `incrementOrDecrementPostfixExpression`
	 * Labeled alternative in `KipperParser.postfixExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitIncrementOrDecrementPostfixExpression(ctx: IncrementOrDecrementPostfixExpressionContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * Enter a parse tree produced by the `functionCallPostfixExpression`
	 * Labeled alternative in `KipperParser.postfixExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterFunctionCallPostfixExpression(ctx: FunctionCallPostfixExpressionContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `functionCallPostfixExpression`
	 * Labeled alternative in `KipperParser.postfixExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitFunctionCallPostfixExpression(ctx: FunctionCallPostfixExpressionContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * Enter a parse tree produced by `KipperParser.arraySpecifier`.
	 * @param ctx The parse tree
	 */
	public enterArraySpecifier(ctx: ArraySpecifierContext): void {}

	/**
	 * Exit a parse tree produced by `KipperParser.arraySpecifier`.
	 * @param ctx The parse tree
	 */
	public exitArraySpecifier(ctx: ArraySpecifierContext): void {}

	/**
	 * We are ignoring unary expressions, and only going to handle the rules 'passOnUnaryExpression',
	 * 'incrementOrDecrementUnaryExpression' and 'operatorModifiedUnaryExpression', which implement a more precise
	 * 'unaryExpression' rule.
	 *
	 * This is to simplify the walking process, without having to check if the expression is actually used every time
	 * an expression is called.
	 */

	// /**
	//  * Enter a parse tree produced by `KipperParser.unaryExpression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// enterUnaryExpression(ctx: UnaryExpressionContext): void {}
	//
	// /**
	//  * Exit a parse tree produced by `KipperParser.unaryExpression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// exitUnaryExpression(ctx: UnaryExpressionContext): void {}

	/**
	 * Enter a parse tree produced by the `passOnUnaryExpression`
	 * Labeled alternative in `KipperParser.unaryExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterPassOnUnaryExpression: undefined = passOnHandler; // pass on expressions are always ignored

	/**
	 * Exit a parse tree produced by the `passOnUnaryExpression`
	 * Labeled alternative in `KipperParser.unaryExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitPassOnUnaryExpression: undefined = passOnHandler; // pass on expressions are always ignored

	/**
	 * Enter a parse tree produced by the `incrementOrDecrementUnaryExpression`
	 * Labeled alternative in `KipperParser.unaryExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterIncrementOrDecrementUnaryExpression(ctx: IncrementOrDecrementUnaryExpressionContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `incrementOrDecrementUnaryExpression`
	 * Labeled alternative in `KipperParser.unaryExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitIncrementOrDecrementUnaryExpression(ctx: IncrementOrDecrementUnaryExpressionContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * Enter a parse tree produced by the `operatorModifiedUnaryExpression`
	 * Labeled alternative in `KipperParser.unaryExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterOperatorModifiedUnaryExpression(ctx: OperatorModifiedUnaryExpressionContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `operatorModifiedUnaryExpression`
	 * Labeled alternative in `KipperParser.unaryExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitOperatorModifiedUnaryExpression(ctx: OperatorModifiedUnaryExpressionContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * Enter a parse tree produced by `KipperParser.unaryOperator`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterUnaryOperator(ctx: UnaryOperatorContext): void {}

	/**
	 * Exit a parse tree produced by `KipperParser.unaryOperator`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitUnaryOperator(ctx: UnaryOperatorContext): void {}

	/**
	 * We are ignoring cast or convert expressions, and only going to handle the rules 'passOnCastOrConvertExpression',
	 * and 'actualCastOrConvertExpression', which implement a more precise 'castOrConvertExpression' rule.
	 *
	 * This is to simplify the walking process, without having to check if the expression is actually used every time
	 * an expression is called.
	 */

	// /**
	//  * Enter a parse tree produced by `KipperParser.castOrConvertExpression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// enterCastOrConvertExpression(ctx: CastOrConvertExpressionContext): void {}
	//
	// /**
	//  * Exit a parse tree produced by `KipperParser.castOrConvertExpression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// exitCastOrConvertExpression(ctx: CastOrConvertExpressionContext): void {}

	/**
	 * Enter a parse tree produced by the `passOnCastOrConvertExpression`
	 * Labeled alternative in `KipperParser.castOrConvertExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterPassOnCastOrConvertExpression: undefined = passOnHandler; // pass on expressions are always ignored

	/**
	 * Exit a parse tree produced by the `passOnCastOrConvertExpression`
	 * Labeled alternative in `KipperParser.castOrConvertExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitPassOnCastOrConvertExpression: undefined = passOnHandler; // pass on expressions are always ignored

	/**
	 * Enter a parse tree produced by the `actualCastOrConvertExpression`
	 * Labeled alternative in `KipperParser.castOrConvertExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterActualCastOrConvertExpression(ctx: ActualCastOrConvertExpressionContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `actualCastOrConvertExpression`
	 * Labeled alternative in `KipperParser.castOrConvertExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitActualCastOrConvertExpression(ctx: ActualCastOrConvertExpressionContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * We are ignoring multiplicative expressions, and only going to handle the rules 'passOnMultiplicativeExpression',
	 * and 'actualMultiplicativeExpression', which implement a more precise 'multiplicativeExpression' rule.
	 *
	 * This is to simplify the walking process, without having to check if the expression is actually used every time
	 * an expression is called.
	 */

	// /**
	//  * Enter a parse tree produced by `KipperParser.multiplicativeExpression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// enterMultiplicativeExpression(ctx: MultiplicativeExpressionContext): void {}
	//
	// /**
	//  * Exit a parse tree produced by `KipperParser.multiplicativeExpression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// exitMultiplicativeExpression(ctx: MultiplicativeExpressionContext): void {}

	/**
	 * Enter a parse tree produced by the `passOnMultiplicativeExpression`
	 * Labeled alternative in `KipperParser.multiplicativeExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterPassOnMultiplicativeExpression: undefined = passOnHandler; // pass on expressions are always ignored

	/**
	 * Exit a parse tree produced by the `passOnMultiplicativeExpression`
	 * Labeled alternative in `KipperParser.multiplicativeExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitPassOnMultiplicativeExpression: undefined = passOnHandler; // pass on expressions are always ignored

	/**
	 * Enter a parse tree produced by the `actualMultiplicativeExpression`
	 * Labeled alternative in `KipperParser.multiplicativeExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterActualMultiplicativeExpression(ctx: ActualMultiplicativeExpressionContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `actualMultiplicativeExpression`
	 * Labeled alternative in `KipperParser.multiplicativeExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitActualMultiplicativeExpression(ctx: ActualMultiplicativeExpressionContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * We are ignoring additive expressions, and only going to handle the rules 'passOnAdditiveExpression',
	 * and 'actualAdditiveExpression', which implement a more precise 'additiveExpression' rule.
	 *
	 * This is to simplify the walking process, without having to check if the expression is actually used every time
	 * an expression is called.
	 */

	// /**
	//  * Enter a parse tree produced by `KipperParser.additiveExpression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// enterAdditiveExpression(ctx: AdditiveExpressionContext): void {}
	//
	// /**
	//  * Exit a parse tree produced by `KipperParser.additiveExpression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// exitAdditiveExpression(ctx: AdditiveExpressionContext): void {}

	/**
	 * Enter a parse tree produced by the `passOnAdditiveExpression`
	 * Labeled alternative in `KipperParser.additiveExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterPassOnAdditiveExpression: undefined = passOnHandler; // pass on expressions are always ignored

	/**
	 * Exit a parse tree produced by the `passOnAdditiveExpression`
	 * Labeled alternative in `KipperParser.additiveExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitPassOnAdditiveExpression: undefined = passOnHandler; // pass on expressions are always ignored

	/**
	 * Enter a parse tree produced by the `actualAdditiveExpression`
	 * Labeled alternative in `KipperParser.additiveExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterActualAdditiveExpression(ctx: ActualAdditiveExpressionContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `actualAdditiveExpression`
	 * Labeled alternative in `KipperParser.additiveExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitActualAdditiveExpression(ctx: ActualAdditiveExpressionContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * We are ignoring relational expressions, and only going to handle the rules 'passOnRelationalExpression',
	 * and 'actualRelationalExpression', which implement a more precise 'relationalExpression' rule.
	 *
	 * This is to simplify the walking process, without having to check if the expression is actually used every time an
	 * expression is called.
	 */

	// /**
	//  * Enter a parse tree produced by `KipperParser.relationalExpression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// enterRelationalExpression(ctx: RelationalExpressionContext): void {}
	//
	// /**
	//  * Exit a parse tree produced by `KipperParser.relationalExpression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// exitRelationalExpression(ctx: RelationalExpressionContext): void {}

	/**
	 * Enter a parse tree produced by the `passOnRelationalExpression`
	 * Labeled alternative in `KipperParser.relationalExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterPassOnRelationalExpression: undefined = passOnHandler; // pass on expressions are always ignored

	/**
	 * Exit a parse tree produced by the `passOnRelationalExpression`
	 * Labeled alternative in `KipperParser.relationalExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitPassOnRelationalExpression: undefined = passOnHandler; // pass on expressions are always ignored

	/**
	 * Enter a parse tree produced by the `actualRelationalExpression`
	 * Labeled alternative in `KipperParser.relationalExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterActualRelationalExpression(ctx: ActualRelationalExpressionContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `actualRelationalExpression`
	 * Labeled alternative in `KipperParser.relationalExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitActualRelationalExpression(ctx: ActualRelationalExpressionContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * We are ignoring equality expressions, and only going to handle the rules 'passOnEqualityExpression',
	 * and 'actualEqualityExpression', which implement a more precise 'equalityExpression' rule.
	 *
	 * This is to simplify the walking process, without having to check if the expression is actually used every time an
	 * expression is called.
	 */

	// /**
	//  * Enter a parse tree produced by `KipperParser.equalityExpression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// enterEqualityExpression(ctx: EqualityExpressionContext): void {}
	//
	// /**
	//  * Exit a parse tree produced by `KipperParser.equalityExpression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// exitEqualityExpression(ctx: EqualityExpressionContext): void {}

	/**
	 * Enter a parse tree produced by the `passOnEqualityExpression`
	 * Labeled alternative in `KipperParser.equalityExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterPassOnEqualityExpression: undefined = passOnHandler; // pass on expressions are always ignored

	/**
	 * Exit a parse tree produced by the `passOnEqualityExpression`
	 * Labeled alternative in `KipperParser.equalityExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitPassOnEqualityExpression: undefined = passOnHandler; // pass on expressions are always ignored

	/**
	 * Enter a parse tree produced by the `actualEqualityExpression`
	 * Labeled alternative in `KipperParser.equalityExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterActualEqualityExpression(ctx: ActualEqualityExpressionContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `actualEqualityExpression`
	 * Labeled alternative in `KipperParser.equalityExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitActualEqualityExpression(ctx: ActualEqualityExpressionContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * We are ignoring logical and expressions, and only going to handle the rules 'passOnLogicalAndExpression',
	 * and 'actualLogicalAndExpression', which implement a more precise 'logicalAndExpression' rule.
	 *
	 * This is to simplify the walking process, without having to check if the expression is actually used every time an
	 * expression is called.
	 */

	// /**
	//  * Enter a parse tree produced by `KipperParser.logicalAndExpression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// enterLogicalAndExpression(ctx: LogicalAndExpressionContext): void {}
	//
	// /**
	//  * Exit a parse tree produced by `KipperParser.logicalAndExpression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// exitLogicalAndExpression(ctx: LogicalAndExpressionContext): void {}

	/**
	 * Enter a parse tree produced by the `passOnLogicalAndExpression`
	 * Labeled alternative in `KipperParser.logicalAndExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterPassOnLogicalAndExpression: undefined = passOnHandler; // pass on expressions are always ignored

	/**
	 * Exit a parse tree produced by the `passOnLogicalAndExpression`
	 * Labeled alternative in `KipperParser.logicalAndExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitPassOnLogicalAndExpression: undefined = passOnHandler; // pass on expressions are always ignored

	/**
	 * Enter a parse tree produced by the `actualLogicalAndExpression`
	 * Labeled alternative in `KipperParser.logicalAndExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterActualLogicalAndExpression(ctx: ActualLogicalAndExpressionContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `actualLogicalAndExpression`
	 * Labeled alternative in `KipperParser.logicalAndExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitActualLogicalAndExpression(ctx: ActualLogicalAndExpressionContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * We are ignoring logical or expressions, and only going to handle the rules 'passOnLogicalOrExpression',
	 * and 'actualLogicalOrExpression', which implement a more precise 'logicalOrExpression' rule.
	 *
	 * This is to simplify the walking process, without having to check if the expression is actually used every time an
	 * expression is called.
	 */

	// /**
	//  * Enter a parse tree produced by `KipperParser.logicalOrExpression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// enterLogicalOrExpression(ctx: LogicalOrExpressionContext): void {}
	//
	// /**
	//  * Exit a parse tree produced by `KipperParser.logicalOrExpression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// exitLogicalOrExpression(ctx: LogicalOrExpressionContext): void {}

	/**
	 * Enter a parse tree produced by the `passOnLogicalOrExpression`
	 * Labeled alternative in `KipperParser.logicalOrExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterPassOnLogicalOrExpression: undefined = passOnHandler; // pass on expressions are always ignored

	/**
	 * Exit a parse tree produced by the `passOnLogicalOrExpression`
	 * Labeled alternative in `KipperParser.logicalOrExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitPassOnLogicalOrExpression: undefined = passOnHandler; // pass on expressions are always ignored

	/**
	 * Enter a parse tree produced by the `actualLogicalOrExpression`
	 * Labeled alternative in `KipperParser.logicalOrExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterActualLogicalOrExpression(ctx: ActualLogicalOrExpressionContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `actualLogicalOrExpression`
	 * Labeled alternative in `KipperParser.logicalOrExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitActualLogicalOrExpression(ctx: ActualLogicalOrExpressionContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * We are ignoring conditional expressions, and only going to handle the rules 'passOnConditionalExpression',
	 * and 'actualConditionalExpression', which implement a more precise 'conditionalExpression' rule.
	 *
	 * This is to simplify the walking process, without having to check if the expression is actually used every time an
	 * expression is called.
	 */

	// /**
	//  * Enter a parse tree produced by `KipperParser.conditionalExpression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// enterConditionalExpression(ctx: ConditionalExpressionContext): void {}
	//
	// /**
	//  * Exit a parse tree produced by `KipperParser.conditionalExpression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// exitConditionalExpression(ctx: ConditionalExpressionContext): void {}

	/**
	 * Enter a parse tree produced by the `passOnConditionalExpression`
	 * Labeled alternative in `KipperParser.conditionalExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterPassOnConditionalExpression: undefined = passOnHandler; // pass on expressions are always ignored

	/**
	 * Exit a parse tree produced by the `passOnConditionalExpression`
	 * Labeled alternative in `KipperParser.conditionalExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitPassOnConditionalExpression: undefined = passOnHandler; // pass on expressions are always ignored

	/**
	 * Enter a parse tree produced by the `actualConditionalExpression`
	 * Labeled alternative in `KipperParser.conditionalExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterActualConditionalExpression(ctx: ActualConditionalExpressionContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `actualConditionalExpression`
	 * Labeled alternative in `KipperParser.conditionalExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitActualConditionalExpression(ctx: ActualConditionalExpressionContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * We are ignoring assignment expressions, and only going to handle the rules 'passOnAssignmentExpression',
	 * and 'actualAssignmentExpression', which implement a more precise 'assignmentExpression' rule.
	 *
	 * This is to simplify the walking process, without having to check if the expression is actually used every time an
	 * expression is called.
	 */

	// /**
	//  * Enter a parse tree produced by `KipperParser.assignmentExpression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// enterAssignmentExpression(ctx: AssignmentExpressionContext): void {}
	//
	// /**
	//  * Exit a parse tree produced by `KipperParser.assignmentExpression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// exitAssignmentExpression(ctx: AssignmentExpressionContext): void {}

	/**
	 * Enter a parse tree produced by the `passOnAssignmentExpression`
	 * Labeled alternative in `KipperParser.assignmentExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterPassOnAssignmentExpression: undefined = passOnHandler; // pass on expressions are always ignored

	/**
	 * Exit a parse tree produced by the `passOnAssignmentExpression`
	 * Labeled alternative in `KipperParser.assignmentExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitPassOnAssignmentExpression: undefined = passOnHandler; // pass on expressions are always ignored

	/**
	 * Enter a parse tree produced by the `actualAssignmentExpression`
	 * Labeled alternative in `KipperParser.assignmentExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterActualAssignmentExpression(ctx: ActualAssignmentExpressionContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `actualAssignmentExpression`
	 * Labeled alternative in `KipperParser.assignmentExpression`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitActualAssignmentExpression(ctx: ActualAssignmentExpressionContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * Enter a parse tree produced by `KipperParser.assignmentOperator`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterAssignmentOperator(ctx: AssignmentOperatorContext): void {}

	/**
	 * Exit a parse tree produced by `KipperParser.assignmentOperator`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitAssignmentOperator(ctx: AssignmentOperatorContext): void {}

	/**
	 * We are ignoring constant expressions and default expressions, as the children will handle everything.
	 */

	// /**
	//  * Enter a parse tree produced by `KipperParser.constantExpression`.
	//  *
	//  * This is an expression that "re-directs" directly to an {@link ConditionalExpressionContext} and is used inside
	//  * {@link SwitchLabeledStatementContext} (Switch).
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// enterConstantExpression(ctx: ConstantExpressionContext): void {}
	//
	// /**
	//  * Exit a parse tree produced by `KipperParser.constantExpression`.
	//  *
	//  * This is an expression that "re-directs" directly to an {@link ConditionalExpressionContext} and is used inside
	//  * {@link SwitchLabeledStatementContext} (Switch statement).
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// exitConstantExpression(ctx: ConstantExpressionContext): void {}
	//
	// /**
	//  * Enter a parse tree produced by `KipperParser.expression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// enterExpression(ctx: ExpressionContext): void {}
	//
	// /**
	//  * Exit a parse tree produced by `KipperParser.expression`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// exitExpression(ctx: ExpressionContext): void {}

	// -- Statement section --

	/**
	 * We are ignoring statements, and only going to handle the rules 'expressionStatement', 'labeledStatement'
	 * 'selectionStatement', 'iterationStatement', 'jumpStatement' and 'compoundStatement', which implement a more precise
	 * 'assignmentExpression' rule.
	 *
	 * This is to simplify the walking process, without having to check if the expression is actually used every time an
	 * expression is called.
	 */

	// /**
	//  * Enter a parse tree produced by `KipperParser.statement`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// enterStatement(ctx: StatementContext): void {}
	//
	// /**
	//  * Exit a parse tree produced by `KipperParser.statement`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// exitStatement(ctx: StatementContext): void {}

	/**
	 * Enter a parse tree produced by `KipperParser.expressionStatement`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterExpressionStatement(ctx: ExpressionStatementContext): void {
		this.handleIncomingStatementCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by `KipperParser.expressionStatement`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitExpressionStatement(ctx: ExpressionStatementContext): void {
		this.handleExitingStatementOrDefinitionCtx();
	}

	/**
	 * Enter a parse tree produced by `KipperParser.compoundStatement`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterCompoundStatement(ctx: CompoundStatementContext): void {
		this.handleIncomingStatementCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by `KipperParser.compoundStatement`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitCompoundStatement(ctx: CompoundStatementContext): void {
		this.handleExitingStatementOrDefinitionCtx();
	}

	/**
	 * We are ignoring selection statements, and only going to handle the rules 'ifStatement' and 'switchStatement',
	 * which implement a more precise 'assignmentExpression' rule.
	 *
	 * This is to simplify the walking process, without having to check if the expression is actually used every time an
	 * expression is called.
	 */

	// /**
	//  * Enter a parse tree produced by `KipperParser.selectionStatement`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// enterSelectionStatement(ctx: SelectionStatementContext): void {
	// 	throw new Error("Selection statements are not supported yet in Kipper");
	// }
	//
	// /**
	//  * Exit a parse tree produced by `KipperParser.selectionStatement`.
	//  * @param ctx The parse tree (instance of {@link ParserRuleContext})
	//  */
	// exitSelectionStatement(ctx: SelectionStatementContext): void {
	// 	throw new Error("Selection statements are not supported yet in Kipper");
	// }

	/**
	 * Enter a parse tree produced by the `ifStatement`
	 * labeled alternative in `KipperParser.selectionStatement`.
	 * @param ctx the parse tree
	 */
	public enterIfStatement(ctx: IfStatementContext): void {
		this.handleIncomingStatementCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `ifStatement`
	 * labeled alternative in `KipperParser.selectionStatement`.
	 * @param ctx the parse tree
	 */
	public exitIfStatement(ctx: IfStatementContext): void {
		this.handleExitingStatementOrDefinitionCtx();
	}

	/**
	 * Enter a parse tree produced by the `switchStatement`
	 * labeled alternative in `KipperParser.selectionStatement`.
	 * @param ctx the parse tree
	 */
	public enterSwitchStatement(ctx: SwitchStatementContext): void {
		this.handleIncomingStatementCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `switchStatement`
	 * labeled alternative in `KipperParser.selectionStatement`.
	 * @param ctx the parse tree
	 */
	public exitSwitchStatement(ctx: SwitchStatementContext): void {
		this.handleExitingStatementOrDefinitionCtx();
	}

	/**
	 * Enter a parse tree produced by `KipperParser.labeledStatement`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterSwitchLabeledStatement(ctx: SwitchLabeledStatementContext): void {
		// TODO! Implement switch statements
	}

	/**
	 * Exit a parse tree produced by `KipperParser.labeledStatement`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitSwitchLabeledStatement(ctx: SwitchLabeledStatementContext): void {
		// TODO! Implement switch statements
	}

	/**
	 * Enter a parse tree produced by `KipperParser.iterationStatement`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterIterationStatement(ctx: IterationStatementContext): void {
		this.handleIncomingStatementCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by `KipperParser.iterationStatement`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitIterationStatement(ctx: IterationStatementContext): void {
		this.handleExitingStatementOrDefinitionCtx();
	}

	/**
	 * Enter a parse tree produced by `KipperParser.jumpStatement`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterJumpStatement(ctx: JumpStatementContext): void {
		this.handleIncomingStatementCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by `KipperParser.jumpStatement`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitJumpStatement(ctx: JumpStatementContext): void {
		this.handleExitingStatementOrDefinitionCtx();
	}

	// -- VariableDeclaration section --

	/**
	 * Enter a parse tree produced by `KipperParser.declaration`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterDeclaration(ctx: DeclarationContext): void {
		this.handleIncomingDefinitionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by `KipperParser.declaration`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitDeclaration(ctx: DeclarationContext): void {
		this.handleExitingStatementOrDefinitionCtx();
	}

	/**
	 * Enter a parse tree produced by `KipperParser.functionDefinition`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterFunctionDeclaration(ctx: FunctionDeclarationContext): void {
		this.handleIncomingDefinitionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by `KipperParser.functionDefinition`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitFunctionDeclaration(ctx: FunctionDeclarationContext): void {
		this.handleExitingStatementOrDefinitionCtx();
	}

	// -- Child Rules Section --

	/**
	 * Enter a parse tree produced by `KipperParser.storageTypeSpecifier`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterStorageTypeSpecifier(ctx: StorageTypeSpecifierContext): void {}

	/**
	 * Exit a parse tree produced by `KipperParser.storageTypeSpecifier`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitStorageTypeSpecifier(ctx: StorageTypeSpecifierContext): void {}

	/**
	 * Enter a parse tree produced by `KipperParser.declarationSpecifiers`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterDeclarationSpecifiers(ctx: DeclarationSpecifiersContext): void {}

	/**
	 * Exit a parse tree produced by `KipperParser.declarationSpecifiers`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitDeclarationSpecifiers(ctx: DeclarationSpecifiersContext): void {}

	/**
	 * Enter a parse tree produced by `KipperParser.declarationSpecifier`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterDeclarationSpecifier(ctx: DeclarationSpecifierContext): void {}

	/**
	 * Exit a parse tree produced by `KipperParser.declarationSpecifier`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitDeclarationSpecifier(ctx: DeclarationSpecifierContext): void {}

	/**
	 * Enter a parse tree produced by `KipperParser.initDeclarator`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterInitDeclarator(ctx: InitDeclaratorContext): void {}

	/**
	 * Exit a parse tree produced by `KipperParser.initDeclarator`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitInitDeclarator(ctx: InitDeclaratorContext): void {}

	/**
	 * Enter a parse tree produced by the `singleTypeSpecifier`
	 * Labeled alternative in `KipperParser.typeSpecifier`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterSingleTypeSpecifier(ctx: SingleTypeSpecifierContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `singleTypeSpecifier`
	 * Labeled alternative in `KipperParser.typeSpecifier`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitSingleTypeSpecifier(ctx: SingleTypeSpecifierContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * Enter a parse tree produced by the `genericTypeSpecifier`
	 * Labeled alternative in `KipperParser.typeSpecifier`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterGenericTypeSpecifier(ctx: GenericTypeSpecifierContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `genericTypeSpecifier`
	 * Labeled alternative in `KipperParser.typeSpecifier`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitGenericTypeSpecifier(ctx: GenericTypeSpecifierContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * Enter a parse tree produced by the `typeofTypeSpecifier`
	 * Labeled alternative in `KipperParser.typeSpecifier`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterTypeofTypeSpecifier(ctx: TypeofTypeSpecifierContext): void {
		this.handleIncomingExpressionCtx(ctx);
	}

	/**
	 * Exit a parse tree produced by the `typeofTypeSpecifier`
	 * Labeled alternative in `KipperParser.typeSpecifier`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitTypeofTypeSpecifier(ctx: TypeofTypeSpecifierContext): void {
		this.handleExitingExpressionCtx();
	}

	/**
	 * Enter a parse tree produced by `KipperParser.typeSpecifier`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterTypeSpecifier(ctx: TypeSpecifierContext): void {}

	/**
	 * Exit a parse tree produced by `KipperParser.typeSpecifier`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitTypeSpecifier(ctx: TypeSpecifierContext): void {}

	/**
	 * Enter a parse tree produced by `KipperParser.declarator`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterDeclarator(ctx: DeclaratorContext): void {}

	/**
	 * Exit a parse tree produced by `KipperParser.declarator`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitDeclarator(ctx: DeclaratorContext): void {}

	/**
	 * Enter a parse tree produced by `KipperParser.directDeclarator`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterDirectDeclarator(ctx: DirectDeclaratorContext): void {}

	/**
	 * Exit a parse tree produced by `KipperParser.directDeclarator`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitDirectDeclarator(ctx: DirectDeclaratorContext): void {}

	/**
	 * Enter a parse tree produced by `KipperParser.parameterTypeList`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterParameterTypeList(ctx: ParameterTypeListContext): void {}

	/**
	 * Exit a parse tree produced by `KipperParser.parameterTypeList`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitParameterTypeList(ctx: ParameterTypeListContext): void {}

	/**
	 * Enter a parse tree produced by `KipperParser.parameterList`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterParameterList(ctx: ParameterListContext): void {}

	/**
	 * Exit a parse tree produced by `KipperParser.parameterList`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitParameterList(ctx: ParameterListContext): void {}

	/**
	 * Enter a parse tree produced by `KipperParser.parameterDeclaration`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterParameterDeclaration(ctx: ParameterDeclarationContext): void {}

	/**
	 * Exit a parse tree produced by `KipperParser.parameterDeclaration`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitParameterDeclaration(ctx: ParameterDeclarationContext): void {}

	/**
	 * Enter a parse tree produced by `KipperParser.initializer`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public enterInitializer(ctx: InitializerContext): void {}

	/**
	 * Exit a parse tree produced by `KipperParser.initializer`.
	 * @param ctx The parse tree (instance of {@link ParserRuleContext})
	 */
	public exitInitializer(ctx: InitializerContext): void {}
}
