name: "Coverage Badge"

on:
  push:
  pull_request:
  schedule:
    - cron: "38 18 * * 5"

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm test
      - name: Generating coverage badge
        run: npm run cov-badge
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Added coverage report'
          add: './README.md'
          default_author: github_actions
