name: "Size Limit"
on: pull_request
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.0.0
          run_install: |
            - recursive: true
      - name: Setup size-limit
        run: pnpm i
      - uses: andresz1/size-limit-action@v1.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          script: pnpm --filter "@kipper/core" exec size-limit --json
