name: "Size Limit"
on: pull_request
jobs:
  size-limit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install PNPM & dev dependencies
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 8.x.x
          run_install: |
            - recursive: true
      - name: Build project to allow for browserify to run
        run: pnpm build
      - name: Run size-limit
        uses: andresz1/size-limit-action@v1.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          script: pnpm exec size-limit --json
          build_script: browserify # Run 'browserify' before 'size-limit' to ensure that the bundle is up-to-date
